# Generated by Django 2.2 on 2020-09-25 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationfinder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formdata',
            options={'verbose_name_plural': 'Forms data'},
        ),
    ]
