# Generated by Django 2.2 on 2020-09-25 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationfinder', '0002_auto_20200925_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formdata',
            options={'verbose_name': 'Form', 'verbose_name_plural': 'Forms data'},
        ),
    ]
