# Generated by Django 2.2 on 2020-09-25 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationfinder', '0003_auto_20200925_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formdata',
            options={'verbose_name': 'Dataform', 'verbose_name_plural': 'Dataforms'},
        ),
    ]
