# Generated by Django 2.2 on 2020-09-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationfinder', '0005_auto_20200925_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdata',
            name='place1_heigth',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='place1_width',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='place2_heigth',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='place2_width',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='place3_heigth',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='place3_width',
        ),
        migrations.AddField(
            model_name='formdata',
            name='place1_radius',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formdata',
            name='place2_radius',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formdata',
            name='place3_radius',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
