# Generated by Django 2.2 on 2020-10-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationfinder', '0009_auto_20201020_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='place1_radius',
            field=models.FloatField(blank=True, default=-1.0),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='place1_x',
            field=models.FloatField(blank=True, default=10000.0),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='place1_y',
            field=models.FloatField(blank=True, default=10000.0),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='place2_radius',
            field=models.FloatField(blank=True, default=-1.0),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='place2_x',
            field=models.FloatField(blank=True, default=10000.0),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='place2_y',
            field=models.FloatField(blank=True, default=10000.0),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='place3_radius',
            field=models.FloatField(blank=True, default=-1.0),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='place3_x',
            field=models.FloatField(blank=True, default=10000.0),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='place3_y',
            field=models.FloatField(blank=True, default=10000.0),
        ),
    ]
