# Generated by Django 2.2 on 2020-10-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationfinder', '0011_auto_20201023_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='card_name',
            field=models.CharField(default='default name', max_length=30),
        ),
    ]
