# Generated by Django 2.2 on 2020-10-27 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relationfinder', '0012_formdata_card_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(default='default name', max_length=30)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('surname', models.CharField(blank=True, max_length=30, null=True)),
                ('fathername', models.CharField(blank=True, max_length=30, null=True)),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True)),
                ('death_year', models.PositiveIntegerField(blank=True, null=True)),
                ('place1_x', models.FloatField(blank=True, null=True)),
                ('place1_y', models.FloatField(blank=True, null=True)),
                ('place1_radius', models.FloatField(blank=True, null=True)),
                ('place1_start_year', models.PositiveIntegerField(blank=True, null=True)),
                ('place1_end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('place2_x', models.FloatField(blank=True, null=True)),
                ('place2_y', models.FloatField(blank=True, null=True)),
                ('place2_radius', models.FloatField(blank=True, null=True)),
                ('place2_start_year', models.PositiveIntegerField(blank=True, null=True)),
                ('place2_end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('place3_x', models.FloatField(blank=True, null=True)),
                ('place3_y', models.FloatField(blank=True, null=True)),
                ('place3_radius', models.FloatField(blank=True, null=True)),
                ('place3_start_year', models.PositiveIntegerField(blank=True, null=True)),
                ('place3_end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('information', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.AlterField(
            model_name='relation',
            name='found_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fbRelations_set', to='relationfinder.Card'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='reference_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtRelations_set', to='relationfinder.Card'),
        ),
        migrations.DeleteModel(
            name='FormData',
        ),
    ]
