# Generated by Django 2.2 on 2020-11-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationfinder', '0013_auto_20201027_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='found_by',
            new_name='referenced_by',
        ),
        migrations.RenameField(
            model_name='relation',
            old_name='reference_to',
            new_name='referencing',
        ),
        migrations.AddField(
            model_name='relation',
            name='connection_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
