# Generated by Django 2.2 on 2020-11-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationfinder', '0014_auto_20201117_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='relation_level',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AddField(
            model_name='card',
            name='sex',
            field=models.CharField(default='default', max_length=30),
        ),
    ]
